application: crewcatcher
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
# Handler for login and redirection

- url: /stylesheets
  static_dir: stylesheets

- url: /images
  static_dir: images

- url: /scripts
  static_dir: scripts

# Twitter Bootstrap
- url: /bootstrap
  static_dir: bootstrap

# All other pages
- url: /.*
  script: web.app

libraries:
- name: jinja2
  version: latest